using System;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu]
public class ItemDatabase : ScriptableObject
{
    private static ItemDatabase _instance;
    public static ItemDatabase Instance
    {
        get
        {
            if (_instance == null)
                _instance = Resources.Load<ItemDatabase>("ItemDatabase");

            return _instance;
        }
    }

    public List<ItemConfig> items;

    private Dictionary<int, ItemConfig> _map;
    private Dictionary<ItemType, List<ItemConfig>> _byCategory;
    private Dictionary<int, ItemContainer> _emptiedBy;

    // A ScriptableObject and its dictionaries outlive Play Mode, so the cache is
    // dropped on every run — otherwise it stays stale after Rebuild Database.
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
    private static void ResetStatics()
    {
        if (_instance != null)
            _instance.Invalidate();

        _instance = null;
    }

    public void Invalidate()
    {
        _map = null;
        _byCategory = null;
        _emptiedBy = null;
    }

    public void Init()
    {
        _map = new Dictionary<int, ItemConfig>();
        _byCategory = new Dictionary<ItemType, List<ItemConfig>>();
        _emptiedBy = new Dictionary<int, ItemContainer>();

        if (items == null)
            return;

        foreach (ItemConfig item in items)
        {
            // The list is generated by Tools/Items/Rebuild Database and keeps
            // empty entries after an asset is deleted.
            if (item == null)
                continue;

            // A new asset defaults to Id 0, so a forgotten field would silently
            // shadow another item.
            if (_map.TryGetValue(item.Id, out ItemConfig existing))
            {
                Debug.LogError(
                    $"ItemDatabase: duplicate Id {item.Id} — '{item.name}' overrides '{existing.name}'.",
                    item);
            }

            _map[item.Id] = item;

            if (!_byCategory.TryGetValue(item.Category, out List<ItemConfig> list))
            {
                list = new List<ItemConfig>();
                _byCategory[item.Category] = list;
            }

            list.Add(item);

            IndexFills(item);
        }
    }

    // A container only ever declares how it is filled (bucket + Water -> full bucket).
    // The way back is that same table read backwards: whatever lists this item as a
    // fill result is what it empties into, so the empty form lives in one asset only.
    private void IndexFills(ItemConfig item)
    {
        if (item is not ItemContainer container || container.Fills == null)
            return;

        foreach (RefillRecipe recipe in container.Fills)
        {
            if (recipe.Result == null)
                continue;

            if (_emptiedBy.TryGetValue(recipe.Result.Id, out ItemContainer existing))
            {
                Debug.LogError(
                    $"ItemDatabase: '{recipe.Result.name}' is filled by both '{existing.name}' " +
                    $"and '{container.name}' — it cannot empty back into two containers.",
                    recipe.Result);
            }

            _emptiedBy[recipe.Result.Id] = container;
        }
    }

    public ItemConfig Get(int id)
    {
        if (_map == null) Init();

        if (_map.TryGetValue(id, out ItemConfig item))
            return item;

        Debug.LogError($"ItemDatabase: item with ID {id} not found!");
        return null;
    }

    /// <summary>
    /// The container a filled item empties back into, if any container fills into it.
    /// False for one-shot items - a handful of fertiliser leaves nothing behind.
    /// </summary>
    public bool TryGetEmptied(int filledId, out ItemContainer empty)
    {
        if (_emptiedBy == null) Init();

        return _emptiedBy.TryGetValue(filledId, out empty);
    }

    public IReadOnlyList<ItemConfig> GetByCategory(ItemType category)
    {
        if (_byCategory == null) Init();

        return _byCategory.TryGetValue(category, out List<ItemConfig> list)
            ? list
            : Array.Empty<ItemConfig>();
    }
}
