using System;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu]
public class ItemDatabase : ScriptableObject
{
    private static ItemDatabase _instance;
    public static ItemDatabase Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = Resources.Load<ItemDatabase>("ItemDatabase");

                if (_instance == null)
                    Debug.LogError("ItemDatabase.asset not found in Resources!");
            }

            return _instance;
        }
    }

    public List<ItemConfig> items;

    private Dictionary<int, ItemConfig> _map;
    private Dictionary<ItemType, List<ItemConfig>> _byCategory;

    // A ScriptableObject and its dictionaries outlive Play Mode, so the cache is
    // dropped on every run — otherwise it stays stale after Rebuild Database.
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
    private static void ResetStatics()
    {
        if (_instance != null)
            _instance.Invalidate();

        _instance = null;
    }

    public void Invalidate()
    {
        _map = null;
        _byCategory = null;
    }

    public void Init()
    {
        _map = new Dictionary<int, ItemConfig>();
        _byCategory = new Dictionary<ItemType, List<ItemConfig>>();

        if (items == null)
            return;

        foreach (ItemConfig item in items)
        {
            // The list is generated by Tools/Items/Rebuild Database and keeps
            // empty entries after an asset is deleted.
            if (item == null)
                continue;

            // A new asset defaults to Id 0, so a forgotten field would silently
            // shadow another item.
            if (_map.TryGetValue(item.Id, out ItemConfig existing))
            {
                Debug.LogError(
                    $"ItemDatabase: duplicate Id {item.Id} — '{item.name}' overrides '{existing.name}'.",
                    item);
            }

            _map[item.Id] = item;

            if (!_byCategory.TryGetValue(item.Category, out List<ItemConfig> list))
            {
                list = new List<ItemConfig>();
                _byCategory[item.Category] = list;
            }

            list.Add(item);
        }
    }

    public ItemConfig Get(int id)
    {
        if (_map == null) Init();

        if (_map.TryGetValue(id, out ItemConfig item))
            return item;

        Debug.LogError($"ItemDatabase: item with ID {id} not found!");
        return null;
    }

    public IReadOnlyList<ItemConfig> GetByCategory(ItemType category)
    {
        if (_byCategory == null) Init();

        return _byCategory.TryGetValue(category, out List<ItemConfig> list)
            ? list
            : Array.Empty<ItemConfig>();
    }
}
